### PR TITLE
Fix underscore in class names

### LINKED ISSUE #198: Underscore "_" not recognized inside type qualifier
### Description

When a type qualifier starts with "_", it breaks the grammar for the rest of the line.

image

### Fix

I replaced all `[A-Za-z]\\w*` to `[a-zA-Z$_][\\.a-zA-Z0-9$_]*`, and `(\\w+\\.)*[A-Z]+\\w*` to `([a-zA-Z$_][a-zA-Z$_0-9]*\\.)*[A-Z]+\\w*)` it seems fixed.

### PR DESCRIPTION
**Pull request by sadikovi**
### Requirements

* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* All new code requires tests to ensure against regressions

### Description of the Change

I updated patterns that relate to storage types to include underscore wherever it was missing; also updated variable pattern to capture storage types with underscore.

Added unit test.

### Alternate Designs

No alternative designs were considered.

### Benefits

Fixes issue of having package and class names that start with underscore.

### Possible Drawbacks

I had to comment out line 832 in `java-spec.coffee`, "_1" value is now highlighted as `storage.type.java`. I will open issue to fix this later. Should not affect anything else, as far as I am concerned.

### Applicable Issues

Fixes #198

### CODE REVIEW

File: spec/java-spec.coffee [hunk 1]
```diff
@@ -828,8 +828,9 @@ describe 'Java grammar', ->
         {tokens} = grammar.tokenizeLine '1_'
         expect(tokens[0]).toEqual value: '1_', scopes: ['source.java']
 
-        {tokens} = grammar.tokenizeLine '_1'
-        expect(tokens[0]).toEqual value: '_1', scopes: ['source.java']
+        # TODO: Fix this test, currently it has a scope of "storage.type.java", because it starts with underscore.
```
Comment (50Wliu) [inline spec/java-spec.coffee]: This is probably a valid type anyway in Java, right?

Comment (sadikovi) [reply spec/java-spec.coffee]: Yes, it could be.

Comment (sadikovi) [reply spec/java-spec.coffee]: Let me check quickly.

Comment (Arcanemagus) [reply spec/java-spec.coffee]: It at least appears to be a [valid Identifier](https://docs.oracle.com/javase/specs/jls/se12/html/jls-3.html#jls-3.8).

Comment (sadikovi) [reply spec/java-spec.coffee]: Yes, I checked, it is a valid class name. I think I am going to remove the test.
